version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AD_PLATFORM_AWS_REGION=ap-south-1
      - AD_PLATFORM_DEBUG=true
      - AD_PLATFORM_LOG_LEVEL=DEBUG
      - AD_PLATFORM_REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=ap-south-1
    depends_on:
      - redis
      - localstack
    networks:
      - platform

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A src.processing.worker worker --loglevel=info
    environment:
      - AD_PLATFORM_AWS_REGION=ap-south-1
      - AD_PLATFORM_REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-south-1
    depends_on:
      - redis
      - localstack
    networks:
      - platform

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - platform

  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb,stepfunctions,cloudwatch
      - DEFAULT_REGION=ap-south-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init.sh
    networks:
      - platform

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - platform

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - platform

volumes:
  redis_data:
  localstack_data:

networks:
  platform:
    driver: bridge
